### PR TITLE
Wildcard search support in Find Rooms dialog.

### PR DESCRIPTION
**Pull request by Mattias-Viklund**

### CODE REVIEW

**Comment by Mattias-Viklund** [comment]
#232

**Comment by nschimme** [comment]
We migrated to C++17 so it's highly possible that GCC supports std::regex::multiline

This means that we could just add a boolean to allow pass through of the input regex. We wouldn't have to do any weird escaping then if this boolean is true.

**Comment by nschimme** [comment]
Heh: `// REVISIT: Add another option to support regex where we do not santize the input`

**Comment by Mattias-Viklund** [comment]
> 
> 
> Heh: `// REVISIT: Add another option to support regex where we do not santize the input`
I'll take a look at std::regex::multiline and also see about just making it a boolean.
C++ isn't my strongest suit though hah, but I'll see what I can do.

**Comment by nschimme** [comment]
https://en.cppreference.com/w/cpp/regex/basic_regex/constants

The POSIX style regex is very different from what most people learn these days. If we switch to the multi-line we can simplify a lot.

**Comment by Mattias-Viklund** [comment]
Yeah, that sounds like a very nice feature.
I'll hop on it.

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/2a86a688b81017f0eb61ffafac85bdd73b049484

**Pull request closed without merging**
