### PR TITLE
Fix wall color when special exit is present

### PR DESCRIPTION
**Pull request by teoli2003**
When a special exit is present, 2.3.6 (and maybe others) set the default color for walls to be drawn after the special exit to 'white'.

It should have been 'black'. 

This bug fix it. I wasn't able to trace back where the bug was introduced, it may have been a side effect of another change, likely when High DPI screen support was added.

(There still is another bug where the stipple colors are lost, but it is independent, and I have not yet figured it out)

I have based this PR on top of PR#22 (there only dependency is the bump in version). I can rebase if needed.

### CODE REVIEW

**Comment by nschimme** [comment]
In the past I have waited to bump versions whenever I had the time to do a QA test on Mac/Linux/Windows.

**Comment by nschimme** [comment]
LGTM. Will merge if this wasn't on top of the doors PR.

**Comment by teoli2003** [comment]
I will rebase, removing the version change (proved to be a bad idea) and directly over 3.2.6 :-)

**Comment by teoli2003** [comment]
Rebased done for this one.

**Comment by nschimme** [comment]
👍

**Pull request merged**
